version: '3'
services:
  flask:
    build: .
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    ports:
      - "5000:5000"
    command: python service.py